version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: "
    reviewers:
      - "stepanstipl"
      - "david-doit-intl"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: "
    reviewers:
      - "stepanstipl"
      - "david-doit-intl"
