name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          close-issue-message: 'This Issue was closed because it has been stalled for 30 days with no activity.'
          stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          close-pr-message: 'This PR was closed because it has been stalled for 45 days with no activity.'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          stale-pr-label: 'stale'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
